---

- hosts: debian
  become: yes
  tasks:
  
  - name: Delete content & directory
    file:
      state: absent
      path: /var/www/html


  - name: Install Git
    package:
      name: git
      state: latest

  - name: Clone a github repository
    git:
      repo: https://github.com/jvcano/WEB.git
      dest: /var/www/html/
      clone: yes
      update: yes

  
  - name: latest Apache version installed
    package:
      name: apache2
      state: latest


  - name: Apache enabled and running
    service:
      name: apache2
      enabled: true
      state: reloaded



...