---

- hosts: debian
  become: yes
  tasks:
  
  - name: latest Apache version installed
    yum:
      name: apache2
      state: latest


  - name: Apache enabled and running
    service:
      name: apache2
      enabled: true
      state: started

  - name: Install Git
    package:
      name: git
      state: latest


  - name: Delete content & directory
    file:
      state: absent
      path: /var/www/html


  - name: Clone a github repository
    git:
      repo: https://github.com/jvcano/Resume-cv.git
      dest: /var/www/html/
      clone: yes
      update: yes

  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
      
  

...