---

- hosts: debian
  become: true
  tasks:


  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  

  - name: remove vim package
    apt:
      name: vim
      state: absent

...