---

- hosts: fleet
  become: true
  tasks:


  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Debian"
  

  - name: remove vim package
    apt:
      name: vim
      state: absent
    when: ansible_distribution == "Debian"


  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest  
    when: ansible_distribution == "CentOS"  


  - name: remove vim package
    yum:
      name: vim
      state: absent
    when: ansible_distribution == "CentOS"    
...