---

- hosts: fleet
  become: true
  tasks:


  - name: install apache2 package Debian
    package:
      name: 
        - apache2
        - libapache2-mod-php
        - nano
      state: latest
    when: ansible_distribution == "Debian"
  

  - name: remove vim package Debian
    package:
      name: nano 
      state: absent
    


  - name: Install the latest version of Apache Centos
    yum:
      name: 
        - httpd
        - php 
        - python-pip
      state: latest  
    when: ansible_distribution == "CentOS"

...
